import { CgSortAz, CgSortZa } from 'react-icons/cg';
import { BiSearch, BiUserPlus, BiPhone, BiRefresh } from 'react-icons/bi';
import { MdOutlineEdit, MdDeleteOutline, MdCopyAll } from 'react-icons/md';
import { VscClose } from 'react-icons/vsc';
import { RiContactsBook2Fill, RiEmotionSadLine } from 'react-icons/ri';
import { AiOutlineUser } from 'react-icons/ai';
import { TbFilter } from 'react-icons/tb';

export const IconSortAz = CgSortAz;
export const IconSortZa = CgSortZa;
export const IconSearch = BiSearch;
export const IconEdit = MdOutlineEdit;
export const IconDelete = MdDeleteOutline;
export const IconCopy = MdCopyAll;
export const IconClose = VscClose;
export const IconUserPlus = BiUserPlus;
export const IconContactsBook = RiContactsBook2Fill;
export const IconSmileSad = RiEmotionSadLine;
export const IconUser = AiOutlineUser;
export const IconPhone = BiPhone;
export const IconRefresh = BiRefresh;
export const IconFilter = TbFilter;
